window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["cografya"] = window.KPSS_BANK["cografya"] || []).push(
{ id: "cog-001", konu: "Coğrafi Konum", soru: "Türkiye toprakları başlıca hangi iki kıta üzerinde yer alır?", secenekler: ["Asya - Afrika", "Asya - Avrupa", "Avrupa - Afrika", "Asya - Amerika", "Avrupa - Okyanusya"], dogru: 1, aciklama: "Türkiye, Anadolu (Asya) ve Trakya (Avrupa) olmak üzere iki kıta üzerinde yer alır." },
{ id: "cog-002", konu: "Coğrafi Konum", soru: "Aşağıdakilerden hangisi Türkiye'yi çevreleyen denizlerden biri değildir?", secenekler: ["Karadeniz", "Akdeniz", "Ege Denizi", "Kızıldeniz", "Marmara Denizi"], dogru: 3, aciklama: "Türkiye'nin üç tarafı Karadeniz, Akdeniz ve Ege denizleriyle çevrilidir; Marmara da iç denizidir. Kızıldeniz ise Türkiye kıyısı olmayan bir denizdir." },
{ id: "cog-003", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de Karadeniz kıyılarında her mevsim yağış görülür. Bu bölgede etkili olan iklim aşağıdakilerden hangisidir?", secenekler: ["Karadeniz iklimi", "Çöl iklimi", "Ekvatoral iklim", "Tundra iklimi", "Muson iklimi"], dogru: 0, aciklama: "Karadeniz kıyılarında her mevsim yağışlı olan Karadeniz iklimi görülür; dağların kıyıya paralel uzanması bu yağışı artırır." },
{ id: "cog-004", konu: "İklim ve Bitki Örtüsü", soru: "Akdeniz ikliminin doğal bitki örtüsü aşağıdakilerden hangisidir?", secenekler: ["Bozkır", "Maki", "Tayga", "Tundra", "Savan"], dogru: 1, aciklama: "Maki, Akdeniz ikliminin doğal bitki örtüsüdür; kuraklığa dayanıklı, kışın yaprağını dökmeyen kısa boylu çalılardan oluşur." },
{ id: "cog-005", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de yıllık yağış miktarının en fazla olduğu bölge aşağıdakilerden hangisidir?", secenekler: ["İç Anadolu", "Güneydoğu Anadolu", "Doğu Karadeniz", "Konya çevresi", "Tuz Gölü çevresi"], dogru: 2, aciklama: "Doğu Karadeniz kıyıları, dağların kıyıya paralel uzanması ve nemli havanın yükselmesi nedeniyle en fazla yağış alan yöredir." },
{ id: "cog-006", konu: "Yer Şekilleri", soru: "Türkiye'nin en yüksek dağı aşağıdakilerden hangisidir?", secenekler: ["Uludağ", "Erciyes Dağı", "Kaçkar Dağı", "Ağrı Dağı", "Süphan Dağı"], dogru: 3, aciklama: "Türkiye'nin en yüksek dağı yaklaşık 5137 metre ile Ağrı Dağı'dır; volkanik kökenlidir." },
{ id: "cog-007", konu: "Yer Şekilleri", soru: "Türkiye'nin yüzölçümü en büyük gölü aşağıdakilerden hangisidir?", secenekler: ["Van Gölü", "Tuz Gölü", "Beyşehir Gölü", "Sapanca Gölü", "İznik Gölü"], dogru: 0, aciklama: "Van Gölü, Türkiye'nin yüzölçümü en büyük gölüdür; suları sodalıdır." },
{ id: "cog-008", konu: "Yer Şekilleri", soru: "Suları tümüyle Türkiye sınırları içinde olan en uzun akarsu aşağıdakilerden hangisidir?", secenekler: ["Fırat", "Dicle", "Meriç", "Aras", "Kızılırmak"], dogru: 4, aciklama: "Kızılırmak, kaynağı ve denize döküldüğü yeri Türkiye içinde bulunan en uzun akarsudur." },
{ id: "cog-009", konu: "Nüfus ve Yerleşme", soru: "Türkiye'de nüfusu en fazla olan il aşağıdakilerden hangisidir?", secenekler: ["Ankara", "İzmir", "İstanbul", "Bursa", "Antalya"], dogru: 2, aciklama: "İstanbul, sanayi ve ticaretin yoğunlaştığı bir merkez olması nedeniyle Türkiye'nin nüfusu en fazla olan ilidir." },
{ id: "cog-010", konu: "Nüfus ve Yerleşme", soru: "Türkiye'de kırsal alanlardan kentlere doğru yaşanan nüfus hareketine ne ad verilir?", secenekler: ["Dış göç", "İç göç", "Mevsimlik turizm", "Doğal afet", "İhracat"], dogru: 1, aciklama: "Bir ülke içinde kırsaldan kente ya da bölgeler arasında yaşanan nüfus hareketine iç göç denir." },
{ id: "cog-011", konu: "Tarım ve Hayvancılık", soru: "Türkiye'de çay üretiminin büyük bölümü hangi bölgede yapılır?", secenekler: ["Akdeniz Bölgesi", "İç Anadolu Bölgesi", "Marmara Bölgesi", "Güneydoğu Anadolu Bölgesi", "Doğu Karadeniz kıyıları"], dogru: 4, aciklama: "Çay, nemli ve ılıman iklim istediğinden Doğu Karadeniz kıyılarında (özellikle Rize çevresinde) yetiştirilir." },
{ id: "cog-012", konu: "Tarım ve Hayvancılık", soru: "Fındık üretimiyle ünlü olan ve dünya üretiminde ilk sırada yer aldığımız bölge aşağıdakilerden hangisidir?", secenekler: ["Karadeniz Bölgesi", "İç Anadolu Bölgesi", "Akdeniz Bölgesi", "Ege Bölgesi", "Doğu Anadolu Bölgesi"], dogru: 0, aciklama: "Fındık, nemli ve ılıman Karadeniz kıyılarında yetişir; Türkiye dünya fındık üretiminde birincidir." },
{ id: "cog-013", konu: "Madenler, Enerji ve Sanayi", soru: "Türkiye'nin dünya rezervinde ilk sırada yer aldığı; cam ve seramik yapımında kullanılan maden aşağıdakilerden hangisidir?", secenekler: ["Altın", "Bor", "Petrol", "Elmas", "Gümüş"], dogru: 1, aciklama: "Türkiye, dünya bor rezervinde ilk sıradadır; bor cam, seramik ve kimya sanayisinde kullanılır." },
{ id: "cog-014", konu: "Madenler, Enerji ve Sanayi", soru: "Taş kömürünün çıkarıldığı ve demir-çelik sanayisiyle bilinen ilimiz aşağıdakilerden hangisidir?", secenekler: ["Rize", "Antalya", "Zonguldak", "Muğla", "Aydın"], dogru: 2, aciklama: "Zonguldak, Türkiye'nin en önemli taş kömürü havzasıdır ve yakınındaki demir-çelik tesislerine kaynaklık eder." },
{ id: "cog-015", konu: "Ulaşım, Ticaret ve Turizm", soru: "Türkiye'de yük ve yolcu taşımacılığında en çok kullanılan ulaşım türü aşağıdakilerden hangisidir?", secenekler: ["Denizyolu", "Havayolu", "Demiryolu", "Karayolu", "Boru hattı"], dogru: 3, aciklama: "Karayolu, kapıdan kapıya taşıma esnekliği ve yaygın ağı sayesinde en çok kullanılan ulaşım türüdür." },
{ id: "cog-016", konu: "Ulaşım, Ticaret ve Turizm", soru: "Peribacaları ve balon turlarıyla ünlü, önemli bir turizm merkezi olan yöremiz aşağıdakilerden hangisidir?", secenekler: ["Kapadokya", "Pamukkale", "Efes", "Uludağ", "Ölüdeniz"], dogru: 0, aciklama: "Kapadokya (Nevşehir çevresi), peribacaları ve sıcak hava balonu turlarıyla ünlü bir turizm merkezidir." },
{ id: "cog-017", konu: "Bölgeler ve Projeler", soru: "Türkiye'nin yüzölçümü en büyük coğrafi bölgesi aşağıdakilerden hangisidir?", secenekler: ["Marmara Bölgesi", "Ege Bölgesi", "Doğu Anadolu Bölgesi", "Karadeniz Bölgesi", "İç Anadolu Bölgesi"], dogru: 2, aciklama: "Doğu Anadolu Bölgesi, yüzölçümü en büyük; aynı zamanda en yüksek ve en seyrek nüfuslu bölgemizdir." },
{ id: "cog-018", konu: "Bölgeler ve Projeler", soru: "Türkiye'de sanayinin en yoğun olduğu ve en çok göç alan bölge aşağıdakilerden hangisidir?", secenekler: ["Doğu Anadolu Bölgesi", "Güneydoğu Anadolu Bölgesi", "Karadeniz Bölgesi", "İç Anadolu Bölgesi", "Marmara Bölgesi"], dogru: 4, aciklama: "Marmara Bölgesi, sanayinin en yoğun olduğu ve iş olanakları nedeniyle en çok göç alan bölgedir." }
);
