window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["cografya"] = window.KPSS_BANK["cografya"] || []).push(
{ id: "cog-073", konu: "Coğrafi Konum", soru: "Türkiye'nin en doğusunda yer alan ilimiz aşağıdakilerden hangisidir?", secenekler: ["Edirne", "Iğdır", "Sinop", "Antalya", "İzmir"], dogru: 1, aciklama: "Türkiye'nin en doğusundaki noktası Iğdır ilinde bulunur. En batıdaki nokta ise Edirne'dedir." },
{ id: "cog-074", konu: "Coğrafi Konum", soru: "Türkiye'nin batı ucunda yer alan ve Avrupa'ya kara sınırı olan ilimiz aşağıdakilerden hangisidir?", secenekler: ["Edirne", "Iğdır", "Van", "Kars", "Hakkâri"], dogru: 0, aciklama: "Edirne, Türkiye'nin batı ucunda yer alır ve Yunanistan ile Bulgaristan'a kara sınırı olan ilimizdir." },
{ id: "cog-075", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de yaz kuraklığının belirgin, yıllık yağışın en az olduğu bölge aşağıdakilerden hangisidir?", secenekler: ["Karadeniz Bölgesi", "Doğu Karadeniz kıyıları", "Marmara Bölgesi", "İç Anadolu Bölgesi", "Batı Karadeniz"], dogru: 3, aciklama: "İç Anadolu Bölgesi, çevresinin dağlarla çevrili olması nedeniyle denizlerin nemli havasından yararlanamaz; bu yüzden en az yağış alan ve yaz kuraklığının belirgin olduğu bölgedir." },
{ id: "cog-076", konu: "İklim ve Bitki Örtüsü", soru: "Denizden uzak iç kesimlerde sıcaklığın yazın çok yükselip kışın çok düşmesine, yani sıcaklık farkının artmasına ne ad verilir?", secenekler: ["Enlem etkisi", "Karasallık", "Bakı", "Yükselti", "Rüzgâr"], dogru: 1, aciklama: "Karasallık, denizden uzaklaşıldıkça iklimin sertleşmesi (yaz-kış sıcaklık farkının artması) durumudur; iç bölgelerde etkilidir." },
{ id: "cog-077", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de kısa mesafelerde bile farklı iklimlerin görülebilmesinin (iklim çeşitliliğinin) temel nedeni aşağıdakilerden hangisidir?", secenekler: ["Ülkenin çok küçük olması", "Nüfusun az olması", "Yüzey şekillerinin (dağ, ova, plato) çeşitli olması", "Hiç denizinin olmaması", "Bir çöl ülkesi olması"], dogru: 2, aciklama: "Türkiye'de dağların uzanışı, yükselti farkları ve denizlere göre konum gibi yüzey şekli özellikleri, kısa mesafelerde bile iklim çeşitliliğine yol açar." },
{ id: "cog-078", konu: "Yer Şekilleri", soru: "Akarsuların hızlı aktığı, eğimin fazla olduğu yerlerde barajlar kurularak hangi enerji türü üretilebilir?", secenekler: ["Petrol", "Kömür", "Doğal gaz", "Nükleer enerji", "Hidroelektrik enerji"], dogru: 4, aciklama: "Eğimin fazla ve suyun bol olduğu akarsular üzerinde kurulan barajlarla hidroelektrik enerji üretilir; Türkiye bu potansiyel bakımından zengindir." },
{ id: "cog-079", konu: "Yer Şekilleri", soru: "Kara ile denizin birbirine değdiği sınıra ne ad verilir?", secenekler: ["Zirve", "Kıyı", "Vadi", "Plato", "Ova"], dogru: 1, aciklama: "Kıyı, kara ile denizin birleştiği sınırdır. Türkiye'nin farklı kıyı tipleri, turizm ve ulaşım açısından önem taşır." },
{ id: "cog-080", konu: "Yer Şekilleri", soru: "Türkiye'nin ikinci büyük gölü olan ve tuz üretimiyle bilinen göl aşağıdakilerden hangisidir?", secenekler: ["Van Gölü", "Beyşehir Gölü", "Tuz Gölü", "Eğirdir Gölü", "Sapanca Gölü"], dogru: 2, aciklama: "Tuz Gölü, İç Anadolu'da yer alan, yüzölçümü bakımından Türkiye'nin ikinci büyük gölüdür ve önemli bir tuz üretim alanıdır." },
{ id: "cog-081", konu: "Nüfus ve Yerleşme", soru: "İnsanların çeşitli nedenlerle yaşadıkları yeri bırakıp başka bir yere gitmesine ne ad verilir?", secenekler: ["Doğum", "Ölüm", "Yağış", "Göç", "İhracat"], dogru: 3, aciklama: "Göç, insanların ekonomik, sosyal ya da doğal nedenlerle yaşadıkları yerden başka bir yere gitmesidir." },
{ id: "cog-082", konu: "Nüfus ve Yerleşme", soru: "Türkiye'de nüfusun seyrek olduğu yerlerin ortak özelliği aşağıdakilerden hangisidir?", secenekler: ["Verimli ova olması", "Sanayinin gelişmiş olması", "Yüksek, engebeli ve sert iklimli olması", "İş imkânının bol olması", "Deniz kıyısında bulunması"], dogru: 2, aciklama: "Nüfusun seyrek olduğu yerler genellikle yüksek, engebeli ve iklimi sert olan; tarım ve ulaşımın zor olduğu alanlardır (Doğu Anadolu gibi)." },
{ id: "cog-083", konu: "Tarım ve Hayvancılık", soru: "Üzüm, incir ve zeytin gibi ürünlerin bol yetiştiği bölgemiz aşağıdakilerden hangisidir?", secenekler: ["Ege Bölgesi", "Doğu Anadolu Bölgesi", "Karadeniz Bölgesi", "İç Anadolu Bölgesi", "Güneydoğu Anadolu Bölgesi"], dogru: 0, aciklama: "Ege Bölgesi; elverişli iklimi sayesinde üzüm, incir ve zeytin üretiminde öne çıkan bir bölgemizdir." },
{ id: "cog-084", konu: "Tarım ve Hayvancılık", soru: "Otu bol yaylalarda, doğal çayır ve meralara dayalı olarak yapılan hayvancılık türü aşağıdakilerden hangisidir?", secenekler: ["Balıkçılık", "Ağır sanayi", "Seracılık", "Mera (otlak) hayvancılığı", "Arıcılık"], dogru: 3, aciklama: "Mera (otlak) hayvancılığı, hayvanların doğal çayır ve otlaklarda otlatılmasına dayanır; Doğu Anadolu'nun geniş yaylalarında yaygındır." },
{ id: "cog-085", konu: "Madenler, Enerji ve Sanayi", soru: "Aşağıdakilerden hangisi bir enerji kaynağı (fosil yakıt) olarak kullanılır?", secenekler: ["Bor", "Demir", "Petrol", "Bakır", "Krom"], dogru: 2, aciklama: "Petrol, ulaşım ve sanayide kullanılan önemli bir enerji kaynağıdır (fosil yakıt). Bor, demir, bakır ve krom ise madendir." },
{ id: "cog-086", konu: "Madenler, Enerji ve Sanayi", soru: "Bir ülkede sanayinin gelişmesi, aşağıdakilerden hangisine yol açar?", secenekler: ["İş imkânlarının artmasına", "Nüfusun tümüyle azalmasına", "Tarımın tek geçim kaynağı hâline gelmesine", "Kırsal nüfusun sürekli artmasına", "İhracatın tamamen bitmesine"], dogru: 0, aciklama: "Sanayinin gelişmesi yeni iş alanları açar, istihdamı artırır ve ülke ekonomisine katkı sağlar." },
{ id: "cog-087", konu: "Ulaşım, Ticaret ve Turizm", soru: "Türkiye'nin tarihî, doğal ve kültürel zenginliklerinin çok olması özellikle hangi sektörü olumlu etkiler?", secenekler: ["Madencilik", "Turizm", "Balıkçılık", "Ormancılık", "Bankacılık"], dogru: 1, aciklama: "Zengin tarihî, doğal ve kültürel değerler turizmi olumlu etkiler; Türkiye bu değerleri sayesinde önemli bir turizm ülkesidir." },
{ id: "cog-088", konu: "Ulaşım, Ticaret ve Turizm", soru: "Kış sporları ve kayak turizmiyle ünlü Uludağ hangi ilimizdedir?", secenekler: ["Antalya", "İzmir", "Denizli", "Nevşehir", "Bursa"], dogru: 4, aciklama: "Uludağ, kış sporları ve kayak turizmiyle ünlü bir merkez olup Bursa ilinde bulunur." },
{ id: "cog-089", konu: "Bölgeler ve Projeler", soru: "Türkiye'nin coğrafi bölgelerinden hangileri adını kıyısında bulunduğu denizden ya da bölgeden almıştır?", secenekler: ["İç Anadolu ve Doğu Anadolu", "Güneydoğu Anadolu ve İç Anadolu", "Yalnızca Marmara", "Yalnızca Ege", "Marmara, Ege, Karadeniz ve Akdeniz"], dogru: 4, aciklama: "Marmara, Ege, Karadeniz ve Akdeniz bölgeleri adını kıyısındaki denizden alır. İç Anadolu, Doğu Anadolu ve Güneydoğu Anadolu ise konumlarına göre adlandırılmıştır." },
{ id: "cog-090", konu: "Bölgeler ve Projeler", soru: "Bir yerin bir coğrafi bölge olarak adlandırılmasında aşağıdakilerden hangisi belirleyicidir?", secenekler: ["Yalnızca nüfus sayısı", "Yüzey şekilleri, iklim ve konum gibi ortak özellikler", "Yalnızca bölgenin adı", "Yalnızca bir bayrağının olması", "Yalnızca konuşulan dil"], dogru: 1, aciklama: "Coğrafi bölgeler; yüzey şekilleri, iklim, bitki örtüsü ve konum gibi ortak doğal ve beşeri özelliklere göre belirlenir." }
);
