window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["cografya"] = window.KPSS_BANK["cografya"] || []).push(
{ id: "cog-037", konu: "Coğrafi Konum", soru: "Türkiye'nin Ekvator'a göre konumu nasıldır?", secenekler: ["Ekvator'un kuzeyindedir", "Ekvator'un güneyindedir", "Ekvator çizgisi üzerindedir", "Kuzey Kutbu'ndadır", "Güney Kutbu'ndadır"], dogru: 0, aciklama: "Türkiye, Ekvator'un kuzeyinde, Kuzey Yarım Küre'de yer alır." },
{ id: "cog-038", konu: "Coğrafi Konum", soru: "Bir yerin, dünya üzerinde enlem ve boylam değerleriyle belirtilen kesin yerine ne ad verilir?", secenekler: ["Özel konum", "Matematik (mutlak) konum", "Bakı", "Yükselti", "Yer şekli"], dogru: 1, aciklama: "Matematik (mutlak) konum, bir yerin enlem ve boylam değerleriyle belirtilen kesin yeridir. Özel konum ise bir yerin denizlere, kıtalara ve komşularına göre konumudur." },
{ id: "cog-039", konu: "İklim ve Bitki Örtüsü", soru: "Ege ve Akdeniz kıyılarında yazın sıcak ve kurak, kışın ılık ve yağışlı geçen iklim tipi aşağıdakilerden hangisidir?", secenekler: ["Karasal iklim", "Karadeniz iklimi", "Akdeniz iklimi", "Tundra iklimi", "Çöl iklimi"], dogru: 2, aciklama: "Akdeniz iklimi; Ege ve Akdeniz kıyılarında görülür, yazları sıcak-kurak, kışları ılık-yağışlıdır." },
{ id: "cog-040", konu: "İklim ve Bitki Örtüsü", soru: "İç bölgelerde görülen bozkır (step) bitki örtüsü, hangi iklimin doğal bitki örtüsüdür?", secenekler: ["Akdeniz iklimi", "Karadeniz iklimi", "Ekvatoral iklim", "Karasal iklim", "Muson iklimi"], dogru: 3, aciklama: "Bozkır (step), yazın kuruyan otsu bitkilerden oluşur ve karasal iklimin doğal bitki örtüsüdür." },
{ id: "cog-041", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de kışın en soğuk geçen ve sıcaklığın en düşük olduğu bölge aşağıdakilerden hangisidir?", secenekler: ["Akdeniz Bölgesi", "Ege Bölgesi", "Marmara Bölgesi", "Karadeniz kıyıları", "Doğu Anadolu Bölgesi"], dogru: 4, aciklama: "Doğu Anadolu Bölgesi, yüksek ve karasal olması nedeniyle kışları en soğuk geçen, sıcaklığın en düşük olduğu bölgemizdir." },
{ id: "cog-042", konu: "Yer Şekilleri", soru: "Etrafı karayla çevrili büyük su birikintilerine ne ad verilir?", secenekler: ["Deniz", "Okyanus", "Akarsu", "Göl", "Boğaz"], dogru: 3, aciklama: "Göl, etrafı karayla çevrili durgun su kütlesidir. Van Gölü ve Tuz Gölü buna örnektir." },
{ id: "cog-043", konu: "Yer Şekilleri", soru: "Denizin karaya doğru sokulduğu, iki yanı karayla çevrili girintiye ne ad verilir?", secenekler: ["Yarımada", "Körfez", "Ada", "Zirve", "Ova"], dogru: 1, aciklama: "Körfez, denizin karaya doğru sokulduğu girintidir. İzmit ve İzmir körfezleri buna örnektir. Yarımada ise üç tarafı denizle çevrili kara parçasıdır." },
{ id: "cog-044", konu: "Yer Şekilleri", soru: "Türkiye'nin en uzun akarsuyu olan Kızılırmak hangi denize dökülür?", secenekler: ["Akdeniz", "Ege Denizi", "Karadeniz", "Marmara Denizi", "Van Gölü"], dogru: 2, aciklama: "Kızılırmak, İç Anadolu'dan doğar ve Karadeniz'e (Bafra Ovası'ndan) dökülür." },
{ id: "cog-045", konu: "Nüfus ve Yerleşme", soru: "Belirli bir alanda yaşayan insan topluluğunun tümüne ne ad verilir?", secenekler: ["Göç", "Yerleşme", "Nüfus", "İklim", "Sanayi"], dogru: 2, aciklama: "Nüfus, belirli bir alanda (ülke, bölge, şehir) yaşayan insanların toplamıdır." },
{ id: "cog-046", konu: "Nüfus ve Yerleşme", soru: "Türkiye'de dağlık ve engebeli yörelerde nüfus genel olarak nasıldır?", secenekler: ["Çok yoğundur", "Seyrektir (azdır)", "Hiç yoktur", "Yalnızca yazın vardır", "En kalabalıktır"], dogru: 1, aciklama: "Dağlık ve engebeli yerlerde tarım ve ulaşım zor olduğundan nüfus seyrektir; düz ve verimli ovalarda ise nüfus daha yoğundur." },
{ id: "cog-047", konu: "Tarım ve Hayvancılık", soru: "Sıcak iklim isteyen ve Anamur çevresinde yetiştirilen tropikal meyve aşağıdakilerden hangisidir?", secenekler: ["Elma", "Muz", "Fındık", "Çay", "Kiraz"], dogru: 1, aciklama: "Muz, sıcak iklim isteyen bir üründür ve Türkiye'de özellikle Anamur (Mersin) çevresinde yetiştirilir." },
{ id: "cog-048", konu: "Tarım ve Hayvancılık", soru: "Türkiye'de tarımda makineleşmenin artması aşağıdakilerden hangisine yol açmıştır?", secenekler: ["Nüfusun tümüyle azalmasına", "Denizlerin kirlenmesine", "Yağışın artmasına", "Kırdan kente göçün artmasına", "Dağların yükselmesine"], dogru: 3, aciklama: "Tarımda makineleşme, kırsalda iş gücüne olan ihtiyacı azaltmış; bu da kırdan kente göçün artmasına yol açmıştır." },
{ id: "cog-049", konu: "Madenler, Enerji ve Sanayi", soru: "Yer altındaki sıcak sulardan yararlanılarak ısınmada ve elektrik üretiminde kullanılan yenilenebilir enerji türü aşağıdakilerden hangisidir?", secenekler: ["Jeotermal enerji", "Kömür", "Petrol", "Doğal gaz", "Nükleer enerji"], dogru: 0, aciklama: "Jeotermal enerji, yer altındaki sıcak su ve buhardan elde edilen yenilenebilir bir enerji türüdür; Türkiye bu kaynak bakımından zengindir." },
{ id: "cog-050", konu: "Madenler, Enerji ve Sanayi", soru: "Bir fabrikanın kurulacağı yer seçilirken aşağıdakilerden hangisi önemli değildir?", secenekler: ["Ham maddeye yakınlık", "Ulaşım kolaylığı", "İş gücünün bulunması", "Pazara yakınlık", "Bölgedeki dağların adı"], dogru: 4, aciklama: "Sanayi tesisleri kurulurken ham madde, ulaşım, iş gücü ve pazara yakınlık önemlidir. Dağların adı ise kuruluş yeri seçiminde bir etken değildir." },
{ id: "cog-051", konu: "Ulaşım, Ticaret ve Turizm", soru: "Bir ülkenin başka ülkelerden mal satın almasına ne ad verilir?", secenekler: ["İhracat", "İthalat", "Üretim", "Göç", "Turizm"], dogru: 1, aciklama: "İthalat, bir ülkenin dışarıdan mal veya hizmet satın almasıdır; ihracat ise dışarıya mal satmaktır." },
{ id: "cog-052", konu: "Ulaşım, Ticaret ve Turizm", soru: "Bembeyaz travertenleriyle ünlü, önemli bir turizm merkezi olan Pamukkale hangi ilimizdedir?", secenekler: ["Denizli", "Antalya", "Nevşehir", "İzmir", "Muğla"], dogru: 0, aciklama: "Pamukkale, beyaz travertenleri ve termal sularıyla ünlü bir turizm merkezi olup Denizli ilindedir." },
{ id: "cog-053", konu: "Bölgeler ve Projeler", soru: "Türkiye kaç coğrafi bölgeye ayrılmıştır?", secenekler: ["5", "6", "7", "8", "9"], dogru: 2, aciklama: "Türkiye, 1941'de belirlenen ölçütlere göre 7 coğrafi bölgeye ayrılmıştır (Marmara, Ege, Akdeniz, Karadeniz, İç Anadolu, Doğu Anadolu, Güneydoğu Anadolu)." },
{ id: "cog-054", konu: "Bölgeler ve Projeler", soru: "Aşağıdakilerden hangisi Türkiye'nin coğrafi bölgelerinden biri DEĞİLDİR?", secenekler: ["Marmara Bölgesi", "Ege Bölgesi", "Akdeniz Bölgesi", "Karadeniz Bölgesi", "Sibirya Bölgesi"], dogru: 4, aciklama: "Sibirya, Türkiye'nin bir coğrafi bölgesi değildir; Rusya'da yer alan bir bölgedir. Türkiye'nin bölgeleri Marmara, Ege, Akdeniz, Karadeniz, İç Anadolu, Doğu Anadolu ve Güneydoğu Anadolu'dur." }
);
