window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["cografya"] = window.KPSS_BANK["cografya"] || []).push(
{ id: "cog-019", konu: "Coğrafi Konum", soru: "Türkiye hangi yarım kürede yer alır?", secenekler: ["Kuzey Yarım Küre", "Güney Yarım Küre", "Kutup bölgesi", "Ekvator çizgisi üzerinde", "Güney Kutbu"], dogru: 0, aciklama: "Türkiye, Ekvator'un kuzeyinde, Kuzey Yarım Küre'de yer alır." },
{ id: "cog-020", konu: "Coğrafi Konum", soru: "Türkiye'nin doğusu ile batısı arasında yerel saat farkı bulunmasının nedeni aşağıdakilerden hangisidir?", secenekler: ["Yükselti farkı", "Boylam (meridyen) farkı", "İklim farkı", "Nüfus farkı", "Deniz farkı"], dogru: 1, aciklama: "Doğu-batı yönündeki yerel saat farkı boylam (meridyen) farkından kaynaklanır; her boylam farkı belirli bir zaman farkı oluşturur." },
{ id: "cog-021", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de dört mevsimin belirgin olarak yaşanmasının temel nedeni aşağıdakilerden hangisidir?", secenekler: ["Ekvator üzerinde bulunması", "Kutup bölgesinde olması", "Orta (ılıman) kuşakta yer alması", "Bir çöl ülkesi olması", "Adalardan oluşması"], dogru: 2, aciklama: "Türkiye orta (ılıman) kuşakta yer aldığı için dört mevsim belirgin biçimde yaşanır." },
{ id: "cog-022", konu: "İklim ve Bitki Örtüsü", soru: "İç Anadolu'da yazların sıcak ve kurak, kışların soğuk geçtiği; sıcaklık farkının fazla olduğu iklim tipi aşağıdakilerden hangisidir?", secenekler: ["Akdeniz iklimi", "Karadeniz iklimi", "Karasal iklim", "Ekvatoral iklim", "Muson iklimi"], dogru: 2, aciklama: "İç bölgelerde görülen karasal iklimde yaz-kış sıcaklık farkı fazladır; doğal bitki örtüsü bozkırdır." },
{ id: "cog-023", konu: "İklim ve Bitki Örtüsü", soru: "Yükseklere çıkıldıkça havanın soğumasının (sıcaklığın azalmasının) nedeni aşağıdakilerden hangisidir?", secenekler: ["Enlem", "Denize uzaklık", "Rüzgârlar", "Yükselti", "Bakı"], dogru: 3, aciklama: "Yükselti arttıkça sıcaklık azalır; genel olarak her 200 metrede sıcaklık yaklaşık 1 °C düşer." },
{ id: "cog-024", konu: "Yer Şekilleri", soru: "Türkiye'nin yer şekilleri genel olarak nasıldır?", secenekler: ["Tamamen düz ovalardan oluşur", "Dağlık ve engebelidir", "Tümüyle çöldür", "Buzullarla kaplıdır", "Tamamen deniz seviyesindedir"], dogru: 1, aciklama: "Türkiye ortalama yükseltisi fazla, dağlık ve engebeli bir ülkedir; bu durum iklimi ve ulaşımı da etkiler." },
{ id: "cog-025", konu: "Yer Şekilleri", soru: "Akarsuların taşıdığı toprakları deniz kıyısında biriktirmesiyle oluşan verimli düzlüklere ne ad verilir?", secenekler: ["Delta ovası", "Plato", "Yayla", "Zirve", "Vadi"], dogru: 0, aciklama: "Delta ovaları, akarsuların alüvyonları deniz kıyısında biriktirmesiyle oluşan verimli düz alanlardır (Çukurova, Bafra gibi)." },
{ id: "cog-026", konu: "Yer Şekilleri", soru: "Türkiye'nin ortalama yükseltisi en fazla, en dağlık bölgesi aşağıdakilerden hangisidir?", secenekler: ["Marmara Bölgesi", "Ege Bölgesi", "Doğu Anadolu Bölgesi", "Akdeniz Bölgesi", "Karadeniz Bölgesi"], dogru: 2, aciklama: "Doğu Anadolu Bölgesi, ortalama yükseltisi en fazla ve en dağlık olan bölgemizdir." },
{ id: "cog-027", konu: "Nüfus ve Yerleşme", soru: "Bir yerde nüfusun sık olmasında etkili olan doğal (fiziki) faktör aşağıdakilerden hangisidir?", secenekler: ["Sanayinin gelişmesi", "Verimli tarım toprakları ve elverişli iklim", "Ticaretin canlı olması", "Turizmin gelişmesi", "Üniversitenin bulunması"], dogru: 1, aciklama: "Nüfusun dağılışını etkileyen doğal faktörler iklim, yer şekli, su ve toprak verimliliğidir. Sanayi, ticaret ve turizm ise beşeri faktörlerdir." },
{ id: "cog-028", konu: "Nüfus ve Yerleşme", soru: "Yüksek, engebeli ve karasal iklimin etkili olduğu; Türkiye'nin en seyrek nüfuslu bölgesi aşağıdakilerden hangisidir?", secenekler: ["Marmara Bölgesi", "Ege Bölgesi", "Akdeniz Bölgesi", "İç Anadolu Bölgesi", "Doğu Anadolu Bölgesi"], dogru: 4, aciklama: "Doğu Anadolu Bölgesi, yüksek ve engebeli yapısı ile sert karasal iklimi nedeniyle en seyrek nüfuslu bölgemizdir." },
{ id: "cog-029", konu: "Tarım ve Hayvancılık", soru: "Türkiye'de en fazla ekilen ve İç Anadolu'ya 'tahıl ambarı' denmesine yol açan ürün aşağıdakilerden hangisidir?", secenekler: ["Buğday", "Çay", "Muz", "Fındık", "Zeytin"], dogru: 0, aciklama: "Buğday, karasal iklime uyum sağladığından en geniş ekim alanına sahiptir; İç Anadolu bu nedenle tahıl ambarı olarak anılır." },
{ id: "cog-030", konu: "Tarım ve Hayvancılık", soru: "Portakal, mandalina gibi turunçgiller genellikle hangi iklimin görüldüğü kıyılarda yetişir?", secenekler: ["Karasal iklim", "Akdeniz iklimi", "Tundra iklimi", "Çöl iklimi", "Kutup iklimi"], dogru: 1, aciklama: "Turunçgiller kışları ılık geçen yerlerde yetişir; bu nedenle Akdeniz ikliminin görüldüğü kıyılarda (Akdeniz ve Ege) yaygındır." },
{ id: "cog-031", konu: "Madenler, Enerji ve Sanayi", soru: "Rüzgâr, güneş ve akarsu gibi doğada sürekli var olan, tükenmeyen enerji kaynaklarına ne ad verilir?", secenekler: ["Fosil yakıtlar", "Kömür", "Petrol", "Doğal gaz", "Yenilenebilir enerji kaynakları"], dogru: 4, aciklama: "Rüzgâr, güneş, su (hidroelektrik) ve jeotermal gibi tükenmeyen kaynaklara yenilenebilir enerji kaynakları denir." },
{ id: "cog-032", konu: "Madenler, Enerji ve Sanayi", soru: "Aşağıdakilerden hangisi yenilenebilir enerji kaynağı değildir?", secenekler: ["Rüzgâr", "Güneş", "Su (hidroelektrik)", "Kömür", "Jeotermal"], dogru: 3, aciklama: "Kömür, milyonlarca yılda oluşan ve tükenebilen bir fosil yakıttır; yenilenebilir değildir. Diğerleri yenilenebilir kaynaklardır." },
{ id: "cog-033", konu: "Ulaşım, Ticaret ve Turizm", soru: "Bir ülkenin ürettiği malları başka ülkelere satmasına ne ad verilir?", secenekler: ["İthalat", "Göç", "İhracat", "Turizm", "Üretim"], dogru: 2, aciklama: "İhracat, bir ülkenin mal veya hizmetlerini başka ülkelere satmasıdır. İthalat ise dışarıdan mal satın almaktır." },
{ id: "cog-034", konu: "Ulaşım, Ticaret ve Turizm", soru: "Deniz-kum-güneş turizmiyle ünlü, yaz aylarında en çok turist çeken kıyılarımız aşağıdakilerden hangisidir?", secenekler: ["Doğu Anadolu kıyıları", "İç Anadolu çevresi", "Kars ve çevresi", "Antalya-Muğla kıyıları", "Erzurum çevresi"], dogru: 3, aciklama: "Antalya ve Muğla gibi Akdeniz-Ege kıyıları, deniz turizmiyle yaz aylarında en çok turist çeken yörelerdir." },
{ id: "cog-035", konu: "Bölgeler ve Projeler", soru: "GAP (Güneydoğu Anadolu Projesi) hangi nehirler üzerinde kurulmuştur?", secenekler: ["Fırat ve Dicle", "Kızılırmak ve Yeşilırmak", "Sakarya ve Meriç", "Aras ve Çoruh", "Gediz ve Menderes"], dogru: 0, aciklama: "GAP, Fırat ve Dicle nehirleri üzerinde sulama ve enerji üretimi amacıyla kurulmuş büyük bir bölgesel kalkınma projesidir." },
{ id: "cog-036", konu: "Bölgeler ve Projeler", soru: "Türkiye'de sanayi ve nüfusun en yoğun olduğu, en çok göç alan bölge aşağıdakilerden hangisidir?", secenekler: ["Doğu Anadolu Bölgesi", "Karadeniz Bölgesi", "İç Anadolu Bölgesi", "Güneydoğu Anadolu Bölgesi", "Marmara Bölgesi"], dogru: 4, aciklama: "Marmara Bölgesi, sanayinin ve nüfusun en yoğun olduğu, iş olanakları nedeniyle en çok göç alan bölgedir." }
);
