window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["cografya"] = window.KPSS_BANK["cografya"] || []).push(
{ id: "cog-055", konu: "Coğrafi Konum", soru: "Türkiye'nin; çevresindeki denizlere, kıtalara ve komşu ülkelere göre konumuna ne ad verilir?", secenekler: ["Özel konum", "Matematik konum", "Enlem", "Boylam", "Yükselti"], dogru: 0, aciklama: "Özel konum, bir yerin denizlere, kıtalara ve komşularına göre konumudur. Matematik konum ise enlem ve boylamla belirtilen kesin yerdir." },
{ id: "cog-056", konu: "Coğrafi Konum", soru: "Aşağıdaki ülkelerden hangisi Türkiye'nin komşusu DEĞİLDİR?", secenekler: ["Almanya", "Yunanistan", "Bulgaristan", "İran", "Suriye"], dogru: 0, aciklama: "Almanya, Türkiye'ye komşu bir ülke değildir. Yunanistan, Bulgaristan, İran ve Suriye ise Türkiye'nin kara komşularındandır." },
{ id: "cog-057", konu: "İklim ve Bitki Örtüsü", soru: "Aşağıdakilerden hangisi bir yerin iklimini etkileyen faktörlerden biri DEĞİLDİR?", secenekler: ["Enlem", "Yükselti", "Denize uzaklık", "Dağların adı", "Bakı"], dogru: 3, aciklama: "İklimi etkileyen faktörler enlem, yükselti, denize uzaklık ve bakıdır. Dağların adı ise iklimi etkileyen bir faktör değildir." },
{ id: "cog-058", konu: "İklim ve Bitki Örtüsü", soru: "Türkiye'de en fazla kar yağışının görüldüğü ve kışın en uzun sürdüğü bölge aşağıdakilerden hangisidir?", secenekler: ["Akdeniz Bölgesi", "Ege Bölgesi", "Doğu Anadolu Bölgesi", "Marmara Bölgesi", "Güneydoğu Anadolu Bölgesi"], dogru: 2, aciklama: "Doğu Anadolu Bölgesi, yüksekliği ve karasal iklimi nedeniyle kar yağışının en fazla ve kışların en uzun olduğu bölgedir." },
{ id: "cog-059", konu: "İklim ve Bitki Örtüsü", soru: "Nemli hava kütlelerinin dağ yamaçları boyunca yükselip soğuyarak yağış bırakmasına ne ad verilir?", secenekler: ["Kar fırtınası", "Sel", "Don olayı", "Sis", "Yamaç (orografik) yağış"], dogru: 4, aciklama: "Yamaç (orografik) yağış, nemli havanın dağ yamaçlarında yükselip soğuyarak yoğuşmasıyla oluşur; Karadeniz kıyılarındaki bol yağışın nedeni budur." },
{ id: "cog-060", konu: "Yer Şekilleri", soru: "Üç tarafı denizlerle çevrili kara parçasına ne ad verilir?", secenekler: ["Yarımada", "Ada", "Körfez", "Boğaz", "Göl"], dogru: 0, aciklama: "Yarımada, üç tarafı denizlerle çevrili, bir tarafı karaya bağlı kara parçasıdır. Ada ise her tarafı suyla çevrilidir." },
{ id: "cog-061", konu: "Yer Şekilleri", soru: "İki denizi birbirine bağlayan dar su geçidine ne ad verilir?", secenekler: ["Körfez", "Ova", "Boğaz", "Yayla", "Vadi"], dogru: 2, aciklama: "Boğaz, iki denizi birbirine bağlayan dar su geçididir. İstanbul ve Çanakkale boğazları buna örnektir." },
{ id: "cog-062", konu: "Yer Şekilleri", soru: "Akarsularla derin biçimde yarılmış, deniz seviyesinden yüksekte bulunan geniş düzlüklere ne ad verilir?", secenekler: ["Delta", "Vadi", "Körfez", "Plato (yayla)", "Ada"], dogru: 3, aciklama: "Plato (yayla), yüksekte bulunan ve akarsu vadileriyle yarılmış geniş düzlüklerdir. İç Anadolu platoları buna örnektir." },
{ id: "cog-063", konu: "Nüfus ve Yerleşme", soru: "Türkiye'de nüfusun yıldan yıla artmasının temel nedeni aşağıdakilerden hangisidir?", secenekler: ["Denizlerin genişlemesi", "Dağların yükselmesi", "Doğumların ölümlerden fazla olması", "İklimin soğuması", "İhracatın artması"], dogru: 2, aciklama: "Bir ülkenin nüfusu, doğumların ölümlerden fazla olmasıyla (doğal nüfus artışı) ve göçlerle artar." },
{ id: "cog-064", konu: "Nüfus ve Yerleşme", soru: "Kırsal alanlardan büyük kentlere yaşanan yoğun göç, kentlerde aşağıdakilerden hangisine yol açar?", secenekler: ["Nüfusun azalmasına", "Çarpık kentleşme ve altyapı sorunlarına", "Tarım alanlarının çoğalmasına", "Ormanların artmasına", "Yağışın artmasına"], dogru: 1, aciklama: "Kentlere yoğun göç; konut, ulaşım ve altyapı yetersizliğine, yani çarpık kentleşme ve çeşitli kent sorunlarına yol açar." },
{ id: "cog-065", konu: "Tarım ve Hayvancılık", soru: "Aşağıdaki tarım ürünlerinden hangisi bir tahıl (hububat) DEĞİLDİR?", secenekler: ["Buğday", "Arpa", "Mısır", "Pamuk", "Çeltik (pirinç)"], dogru: 3, aciklama: "Pamuk bir tahıl değil, tekstil sanayisinin ham maddesi olan bir endüstri bitkisidir. Buğday, arpa, mısır ve çeltik ise tahıldır." },
{ id: "cog-066", konu: "Tarım ve Hayvancılık", soru: "Şeker pancarı, aşağıdaki ürünlerden hangisinin ham maddesidir?", secenekler: ["Şeker", "Zeytinyağı", "Un", "Çay", "Kâğıt"], dogru: 0, aciklama: "Şeker pancarı, şeker üretiminin ham maddesidir; şeker fabrikalarında işlenerek şeker elde edilir." },
{ id: "cog-067", konu: "Madenler, Enerji ve Sanayi", soru: "Ham maddeyi işleyerek kullanılabilir ürünler hâline getiren ekonomik faaliyete ne ad verilir?", secenekler: ["Tarım", "Sanayi (endüstri)", "Turizm", "Hayvancılık", "Ormancılık"], dogru: 1, aciklama: "Sanayi (endüstri), ham maddelerin işlenerek kullanılabilir ürünlere dönüştürüldüğü ekonomik faaliyettir." },
{ id: "cog-068", konu: "Madenler, Enerji ve Sanayi", soru: "Rüzgârın gücünden elektrik üretmek için kurulan yapılar aşağıdakilerden hangisidir?", secenekler: ["Barajlar", "Termik santraller", "Güneş panelleri", "Petrol kuyuları", "Rüzgâr türbinleri"], dogru: 4, aciklama: "Rüzgâr türbinleri, rüzgârın gücüyle dönerek elektrik üretir; bu, yenilenebilir bir enerji kaynağıdır." },
{ id: "cog-069", konu: "Ulaşım, Ticaret ve Turizm", soru: "Uzak mesafeler arasında en hızlı ulaşımı sağlayan ulaşım türü genellikle aşağıdakilerden hangisidir?", secenekler: ["Denizyolu", "Demiryolu", "Karayolu", "Havayolu", "Boru hattı"], dogru: 3, aciklama: "Havayolu, uzak mesafelerde en hızlı ulaşımı sağlayan türdür; ancak maliyeti yüksektir." },
{ id: "cog-070", konu: "Ulaşım, Ticaret ve Turizm", soru: "Antik dünyanın önemli kentlerinden olan Efes, hangi ilimizde bulunur?", secenekler: ["Antalya", "İzmir", "Denizli", "Muğla", "Nevşehir"], dogru: 1, aciklama: "Efes Antik Kenti, İzmir'in Selçuk ilçesinde bulunan, UNESCO Dünya Mirası Listesi'nde yer alan önemli bir turizm merkezidir." },
{ id: "cog-071", konu: "Bölgeler ve Projeler", soru: "Türkiye'nin en batısındaki, Avrupa'ya açılan kapısı konumundaki bölge aşağıdakilerden hangisidir?", secenekler: ["Doğu Anadolu Bölgesi", "Karadeniz Bölgesi", "İç Anadolu Bölgesi", "Akdeniz Bölgesi", "Marmara Bölgesi"], dogru: 4, aciklama: "Marmara Bölgesi, Türkiye'nin en batısında yer alır ve boğazlar ile Avrupa'ya açılan kapısı konumundadır." },
{ id: "cog-072", konu: "Bölgeler ve Projeler", soru: "GAP'ın (Güneydoğu Anadolu Projesi) bölgeye sağladığı en önemli katkı aşağıdakilerden hangisidir?", secenekler: ["Deniz turizmi", "Kış sporları", "Sulama ve enerji üretimi", "Balıkçılık", "Madencilik"], dogru: 2, aciklama: "GAP, Fırat ve Dicle üzerindeki barajlarla sulama ve hidroelektrik enerji üretimi sağlayarak bölgenin kalkınmasına katkıda bulunur." }
);
