window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-007", konu: "Spor", soru: "2025 Avrupa Basketbol Şampiyonası'nda (EuroBasket) Türkiye finale yükselip ikinci olmuştur. Türkiye'yi finalde yenerek şampiyon olan ülke aşağıdakilerden hangisidir?", secenekler: ["Yunanistan", "Almanya", "Fransa", "Sırbistan", "İspanya"], dogru: 1, aciklama: "EuroBasket 2025 finalinde Türkiye A Milli Erkek Basketbol Takımı Almanya'ya yenilerek ikinci olmuş, gümüş madalya kazanmıştır." },
{ id: "gun-008", konu: "Ödüller", soru: "2025 Nobel Barış Ödülü'nü ülkesinde demokrasi mücadelesiyle tanınan hangi Venezuelalı muhalefet lideri kazanmıştır?", secenekler: ["María Corina Machado", "Nicolás Maduro", "Juan Guaidó", "Greta Thunberg", "Malala Yousafzai"], dogru: 0, aciklama: "2025 Nobel Barış Ödülü, Venezuela'da demokratik hakları savunması nedeniyle muhalefet lideri María Corina Machado'ya verilmiştir." },
{ id: "gun-009", konu: "Türkiye Gündemi", soru: "Türkiye'nin uzaya giden (Uluslararası Uzay İstasyonu'na çıkan) ilk astronotu aşağıdakilerden hangisidir?", secenekler: ["Selçuk Bayraktar", "Aziz Sancar", "Alper Gezeravcı", "Cengiz Ultav", "Tuva Cihangir Atasever"], dogru: 2, aciklama: "Türkiye'nin uzaya giden ilk astronotu Alper Gezeravcı'dır; Uluslararası Uzay İstasyonu'nda bilimsel görevler gerçekleştirmiştir." },
{ id: "gun-010", konu: "Kültür-Sanat", soru: "2025 Cannes Film Festivali'nde en büyük ödül olan Altın Palmiye'yi kazanan yönetmen aşağıdakilerden hangisidir?", secenekler: ["Nuri Bilge Ceylan", "Christopher Nolan", "Sean Baker", "Jafar Panahi", "Bong Joon-ho"], dogru: 3, aciklama: "2025 Cannes Film Festivali'nde Altın Palmiye, İranlı yönetmen Jafar Panahi'nin filmine verilmiştir." },
{ id: "gun-011", konu: "Bilim ve Teknoloji", soru: "2025 Nobel Tıp Ödülü hangi konudaki keşiflere verilmiştir?", secenekler: ["Periferik bağışıklık toleransı", "Kanser aşısı geliştirme", "Gen terapisi", "Organ nakli", "Beyin haritalama"], dogru: 0, aciklama: "2025 Nobel Tıp Ödülü, bağışıklık sisteminin kendi dokularına zarar vermesini önleyen periferik bağışıklık toleransı mekanizmasının keşfine verilmiştir." },
{ id: "gun-012", konu: "Uluslararası Gündem", soru: "2025 Kadın Voleybol Dünya Şampiyonası'nda Türkiye A Milli Kadın Voleybol Takımı finalde İtalya'ya yenilerek kaçıncı olmuştur?", secenekler: ["Birinci", "İkinci", "Üçüncü", "Dördüncü", "Beşinci"], dogru: 1, aciklama: "Türkiye A Milli Kadın Voleybol Takımı, 2025 Dünya Şampiyonası finalinde İtalya'ya yenilerek dünya ikincisi olmuştur; bu, takımın tarihindeki en iyi derecedir." }
);
