window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-019", konu: "Bilim ve Teknoloji", soru: "2025 Nobel Fizik Ödülü hangi alandaki keşiflere verilmiştir?", secenekler: ["Elektrik devrelerinde makroskobik kuantum tünelleme", "Kara deliklerin gözlemlenmesi", "Aşı teknolojisi", "Yapay zekâ algoritmaları", "Genetik düzenleme"], dogru: 0, aciklama: "2025 Nobel Fizik Ödülü, bir elektrik devresinde makroskobik kuantum tünelleme ve enerjinin nicelenmesi olaylarının keşfine verilmiştir." },
{ id: "gun-020", konu: "Türkiye Gündemi", soru: "Türkiye'nin yerli ve millî imkânlarla geliştirdiği millî muharip savaş uçağı aşağıdakilerden hangisidir?", secenekler: ["ANKA", "KAAN", "AKINCI", "BAYRAKTAR TB2", "HÜRKUŞ"], dogru: 1, aciklama: "KAAN, Türkiye'nin yerli imkânlarla geliştirdiği millî muharip savaş uçağıdır. ANKA, AKINCI ve BAYRAKTAR TB2 ise insansız hava araçlarıdır; HÜRKUŞ bir eğitim uçağıdır." },
{ id: "gun-021", konu: "Kültür-Sanat", soru: "2025 Eurovision Şarkı Yarışması hangi ülkede (Basel şehrinde) düzenlenmiştir?", secenekler: ["İsveç", "İngiltere", "İsviçre", "İtalya", "İspanya"], dogru: 2, aciklama: "2025 Eurovision Şarkı Yarışması İsviçre'nin Basel kentinde düzenlenmiştir; yarışmayı Avusturya kazanmıştır." },
{ id: "gun-022", konu: "Uluslararası Gündem", soru: "2028 Yaz Olimpiyat Oyunları hangi şehirde düzenlenecektir?", secenekler: ["Paris", "Tokyo", "Londra", "Los Angeles", "Brisbane"], dogru: 3, aciklama: "2028 Yaz Olimpiyat Oyunları, ABD'nin Los Angeles şehrinde düzenlenecektir. 2024'te Paris ev sahipliği yapmıştı." },
{ id: "gun-023", konu: "Türkiye Gündemi", soru: "TOGG, Türkiye'nin yerli imkânlarla ürettiği ilk seri üretim ne aracıdır?", secenekler: ["Otomobil", "Uçak", "Tren", "Gemi", "Helikopter"], dogru: 0, aciklama: "TOGG (Türkiye'nin Otomobili Girişim Grubu), Türkiye'nin yerli ve elektrikli ilk seri üretim otomobilidir." },
{ id: "gun-024", konu: "Ödüller", soru: "Nobel Ödülleri (Barış Ödülü dışında) her yıl hangi ülkenin başkentinde düzenlenen törenle sahiplerine verilir?", secenekler: ["Norveç", "Amerika Birleşik Devletleri", "Fransa", "İngiltere", "İsveç (Stockholm)"], dogru: 4, aciklama: "Nobel Ödülleri, Barış Ödülü dışında İsveç'in başkenti Stockholm'de düzenlenen törenle verilir. Nobel Barış Ödülü ise Norveç'in başkenti Oslo'da verilir." }
);
