window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-013", konu: "Ödüller", soru: "2025 Nobel Edebiyat Ödülü'nü kazanan Macar yazar aşağıdakilerden hangisidir?", secenekler: ["László Krasznahorkai", "Orhan Pamuk", "Jon Fosse", "Han Kang", "Annie Ernaux"], dogru: 0, aciklama: "2025 Nobel Edebiyat Ödülü, Macar yazar László Krasznahorkai'ye verilmiştir. Diğer isimler önceki yıllarda bu ödülü kazanmıştır." },
{ id: "gun-014", konu: "Kültür-Sanat", soru: "2025'te düzenlenen 97. Akademi Ödülleri'nde (Oscar) En İyi Film ödülünü kazanan yapım aşağıdakilerden hangisidir?", secenekler: ["Conclave", "Anora", "Wicked", "The Brutalist", "Emilia Pérez"], dogru: 1, aciklama: "97. Oscar töreninde En İyi Film ödülünü, yönetmenliğini Sean Baker'ın yaptığı 'Anora' kazanmıştır." },
{ id: "gun-015", konu: "Türkiye Gündemi", soru: "2025'te UNESCO Dünya Mirası Listesi'ne eklenen, tarihte ilk madeni paranın basıldığı yer olarak bilinen antik kent aşağıdakilerden hangisidir?", secenekler: ["Efes", "Truva", "Sardes (Sart)", "Bergama", "Afrodisias"], dogru: 2, aciklama: "Sardes (Sart) Antik Kenti, 2025'te UNESCO Dünya Mirası Listesi'ne eklenmiştir; Lidyalıların başkenti olup ilk madeni paranın basıldığı yer olarak bilinir." },
{ id: "gun-016", konu: "Bilim ve Teknoloji", soru: "2025 Nobel Kimya Ödülü hangi konudaki gelişmelere verilmiştir?", secenekler: ["Aşı teknolojisi", "Plastik geri dönüşümü", "Nükleer füzyon", "Metal-organik çerçevelerin (MOF) geliştirilmesi", "Yapay fotosentez"], dogru: 3, aciklama: "2025 Nobel Kimya Ödülü, gözenekli yapıları sayesinde gaz depolama ve su toplama gibi alanlarda kullanılabilen metal-organik çerçevelerin (MOF) geliştirilmesine verilmiştir." },
{ id: "gun-017", konu: "Spor", soru: "2024 UEFA Avrupa Futbol Şampiyonası (EURO 2024) hangi ülkede düzenlenmiştir?", secenekler: ["İngiltere", "İspanya", "Almanya", "Fransa", "İtalya"], dogru: 2, aciklama: "EURO 2024, Almanya'da düzenlenmiştir; turnuvanın şampiyonu ise finalde İngiltere'yi yenen İspanya olmuştur." },
{ id: "gun-018", konu: "Ödüller", soru: "2025 Nobel Ekonomi Ödülü hangi konudaki çalışmalara verilmiştir?", secenekler: ["Enflasyonla mücadele", "İşsizlik politikaları", "Uluslararası ticaret", "Vergi sistemleri", "Yenilik (inovasyon) odaklı ekonomik büyüme"], dogru: 4, aciklama: "2025 Nobel Ekonomi Ödülü, teknolojik yenilik yoluyla sürdürülebilir ekonomik büyümeyi açıklayan çalışmalara verilmiştir." }
);
