window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-025", konu: "Spor", soru: "2025 UEFA Şampiyonlar Ligi'ni tarihinde ilk kez kazanan takım aşağıdakilerden hangisidir?", secenekler: ["Real Madrid", "Manchester City", "Paris Saint-Germain (PSG)", "Bayern Münih", "Inter"], dogru: 2, aciklama: "2025 UEFA Şampiyonlar Ligi finalinde Paris Saint-Germain (PSG), Inter'i 5-0 yenerek kupayı tarihinde ilk kez kazanmıştır." },
{ id: "gun-026", konu: "Uluslararası Gündem", soru: "2026 yılı için 'Dünya Spor Başkenti' unvanına layık görülen şehir aşağıdakilerden hangisidir?", secenekler: ["İstanbul", "Bakü", "Paris", "Londra", "Roma"], dogru: 1, aciklama: "2026 yılı 'Dünya Spor Başkenti' unvanı, Azerbaycan'ın başkenti Bakü'ye verilmiştir." },
{ id: "gun-027", konu: "Türkiye Gündemi", soru: "2026 UEFA Avrupa Ligi finalinin oynanacağı, Türkiye'nin ev sahipliği yapacağı şehir aşağıdakilerden hangisidir?", secenekler: ["İstanbul", "Ankara", "İzmir", "Bursa", "Antalya"], dogru: 0, aciklama: "2026 UEFA Avrupa Ligi finali, İstanbul'daki Beşiktaş Park (Tüpraş) Stadyumu'nda oynanacaktır; bu, Türkiye'nin uluslararası spor organizasyonlarındaki yerini gösterir." },
{ id: "gun-028", konu: "Ödüller", soru: "Her yıl verilen Nobel Ödülleri, aşağıdaki bilim insanlarından hangisinin vasiyeti üzerine düzenlenmeye başlamıştır?", secenekler: ["Albert Einstein", "Marie Curie", "Isaac Newton", "Thomas Edison", "Alfred Nobel"], dogru: 4, aciklama: "Nobel Ödülleri, dinamiti bulan İsveçli bilim insanı ve iş insanı Alfred Nobel'in vasiyeti üzerine verilmeye başlanmıştır." },
{ id: "gun-029", konu: "Kültür-Sanat", soru: "UNESCO'nun Somut Olmayan Kültürel Miras Listesi'nde yer alan, Türkiye'nin geleneksel gölge oyunu aşağıdakilerden hangisidir?", secenekler: ["Bale", "Opera", "Modern tiyatro", "Karagöz ve Hacivat", "Sinema"], dogru: 3, aciklama: "Karagöz ve Hacivat, perde arkasından yansıtılan tasvirlerle oynatılan geleneksel Türk gölge oyunudur ve UNESCO'nun Somut Olmayan Kültürel Miras Listesi'nde yer alır." },
{ id: "gun-030", konu: "Bilim ve Teknoloji", soru: "Türkiye'nin uzay çalışmalarını yürüten ve Millî Uzay Programı'nı koordine eden kurumun kısaltması aşağıdakilerden hangisidir?", secenekler: ["TUA (Türkiye Uzay Ajansı)", "NASA", "ESA", "TSK", "TDK"], dogru: 0, aciklama: "TUA (Türkiye Uzay Ajansı), Türkiye'nin uzay ve havacılık çalışmalarını yürüten ve Millî Uzay Programı'nı koordine eden kurumdur. NASA ABD'nin, ESA ise Avrupa'nın uzay ajansıdır." }
);
