window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["guncel"] = window.KPSS_BANK["guncel"] || []).push(
{ id: "gun-001", konu: "Spor", soru: "2024 Avrupa Futbol Şampiyonası'nı (EURO 2024) kazanan ülke aşağıdakilerden hangisidir?", secenekler: ["İngiltere", "İspanya", "Almanya", "Fransa", "İtalya"], dogru: 1, aciklama: "EURO 2024 finalinde İspanya, İngiltere'yi yenerek şampiyon olmuş ve rekor dördüncü Avrupa şampiyonluğuna ulaşmıştır." },
{ id: "gun-002", konu: "Uluslararası Gündem", soru: "2024 Yaz Olimpiyat Oyunları hangi şehirde düzenlenmiştir?", secenekler: ["Tokyo", "Londra", "Paris", "Roma", "Los Angeles"], dogru: 2, aciklama: "2024 Yaz Olimpiyat Oyunları Fransa'nın başkenti Paris'te düzenlenmiştir; bir sonraki 2028'de Los Angeles'ta yapılacaktır." },
{ id: "gun-003", konu: "Bilim ve Teknoloji", soru: "Türkiye'nin yerli ve millî imkânlarla üretilen ilk haberleşme uydusu aşağıdakilerden hangisidir?", secenekler: ["TÜRKSAT 6A", "RASAT", "GÖKTÜRK-1", "İMECE", "BİLSAT"], dogru: 0, aciklama: "TÜRKSAT 6A, Türkiye'nin yerli ve millî imkânlarla üretilen ilk haberleşme uydusudur." },
{ id: "gun-004", konu: "Spor", soru: "2025 Formula 1 Dünya Şampiyonu olan pilot aşağıdakilerden hangisidir?", secenekler: ["Lewis Hamilton", "Max Verstappen", "Charles Leclerc", "Lando Norris", "Oscar Piastri"], dogru: 3, aciklama: "2025 Formula 1 Dünya Şampiyonu, McLaren pilotu Lando Norris olmuştur; bu, onun ilk şampiyonluğudur." },
{ id: "gun-005", konu: "Türkiye Gündemi", soru: "Havacılık, uzay ve teknoloji festivali TEKNOFEST'in 2026'da düzenleneceği il aşağıdakilerden hangisidir?", secenekler: ["İstanbul", "Ankara", "İzmir", "Bursa", "Şanlıurfa"], dogru: 4, aciklama: "TEKNOFEST 2026'nın Şanlıurfa'da düzenleneceği açıklanmıştır." },
{ id: "gun-006", konu: "Kültür-Sanat", soru: "2025 Eurovision Şarkı Yarışması'nı kazanan ülke aşağıdakilerden hangisidir?", secenekler: ["İsveç", "Avusturya", "İsrail", "İtalya", "İsviçre"], dogru: 1, aciklama: "2025 Eurovision Şarkı Yarışması'nı, sanatçı JJ'in 'Wasted Love' şarkısıyla Avusturya kazanmıştır." }
);
