// Soru bankası dosyalarının listesi. Yeni dosya eklenince bu listeye de eklenir.
window.KPSS_MANIFEST = [
  "matematik-1.js",
  "turkce-1.js",
  "tarih-1.js",
  "cografya-1.js",
  "vatandaslik-1.js",
  "guncel-1.js",
  "matematik-2.js",
  "turkce-2.js",
  "tarih-2.js",
  "cografya-2.js",
  "vatandaslik-2.js",
  "guncel-2.js",
  "matematik-3.js",
  "turkce-3.js",
  "tarih-3.js",
  "cografya-3.js",
  "vatandaslik-3.js",
  "guncel-3.js",
  "matematik-4.js",
  "turkce-4.js",
  "tarih-4.js",
  "cografya-4.js",
  "vatandaslik-4.js",
  "guncel-4.js",
  "turkce-5.js"
];
