window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["vatandaslik"] = window.KPSS_BANK["vatandaslik"] || []).push(
{ id: "vat-019", konu: "Hukukun Temel Kavramları", soru: "Belli bir konuyu düzenleyen, TBMM tarafından çıkarılan yazılı hukuk kurallarına ne ad verilir?", secenekler: ["Kanun", "Gelenek", "Ahlak kuralı", "Görgü kuralı", "Örf"], dogru: 0, aciklama: "Kanun, TBMM tarafından belli bir konuyu düzenlemek için çıkarılan yazılı ve genel hukuk kuralıdır." },
{ id: "vat-020", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre Türkiye Cumhuriyeti'nin resmî dili aşağıdakilerden hangisidir?", secenekler: ["İngilizce", "Türkçe", "Arapça", "Fransızca", "Almanca"], dogru: 1, aciklama: "Anayasa'ya göre Türkiye Cumhuriyeti'nin resmî dili Türkçedir; bu, değiştirilemez maddeler arasında yer alır." },
{ id: "vat-021", konu: "Anayasa ve Genel Esaslar", soru: "Kanunların Anayasa'ya uygun olup olmadığını denetleyen mahkeme aşağıdakilerden hangisidir?", secenekler: ["Yargıtay", "Danıştay", "Anayasa Mahkemesi", "Sayıştay", "Asliye Hukuk Mahkemesi"], dogru: 2, aciklama: "Anayasa Mahkemesi, kanunların ve bazı düzenlemelerin Anayasa'ya uygunluğunu denetler; ayrıca bireysel başvuruları da inceler." },
{ id: "vat-022", konu: "Temel Hak ve Ödevler", soru: "Kişilerin izni ve yasal bir neden olmadan konutlarına girilememesi hangi hakla ilgilidir?", secenekler: ["Seçme hakkı", "Eğitim hakkı", "Vergi ödevi", "Konut dokunulmazlığı", "Askerlik görevi"], dogru: 3, aciklama: "Konut dokunulmazlığı, kişinin evine kendi rızası ve yasal bir neden olmadan girilememesini güvence altına alan bir kişisel haktır." },
{ id: "vat-023", konu: "Temel Hak ve Ödevler", soru: "18 yaşını dolduran her Türk vatandaşının seçimlerde oy kullanabilmesi aşağıdaki haklardan hangisiyle ilgilidir?", secenekler: ["Seçme (oy kullanma) hakkı", "Sağlık hakkı", "Eğitim hakkı", "Çalışma hakkı", "Dinlenme hakkı"], dogru: 0, aciklama: "Seçme (oy kullanma) hakkı, 18 yaşını dolduran her Türk vatandaşının kullanabildiği bir siyasi haktır." },
{ id: "vat-024", konu: "Yasama", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde milletvekili seçilebilmek için en az kaç yaşını doldurmuş olmak gerekir?", secenekler: ["25", "30", "18", "40", "21"], dogru: 2, aciklama: "2017 Anayasa değişikliğiyle milletvekili seçilme yaşı 25'ten 18'e indirilmiştir." },
{ id: "vat-025", konu: "Yürütme", soru: "Bakanlıkların ve kamu kurumlarının, devletin günlük hizmetlerini (eğitim, sağlık, güvenlik gibi) yürüttüğü yapıya ne ad verilir?", secenekler: ["Yasama", "Yargı", "Muhalefet", "İdare (yürütme)", "Seçim kurulu"], dogru: 3, aciklama: "İdare (yürütme), bakanlıklar ve kamu kurumları aracılığıyla devletin kamu hizmetlerini yürüten yapıdır." },
{ id: "vat-026", konu: "Yargı ve İdare", soru: "Bir davada verilen karara itiraz eden tarafın, kararın bir üst mahkemede yeniden incelenmesini istemesine ne ad verilir?", secenekler: ["Af", "İtiraz / temyiz (kanun yolu)", "Ceza", "Uzlaşma", "Ceza indirimi"], dogru: 1, aciklama: "Temyiz (kanun yolu), bir mahkeme kararının hatalı olduğu düşünülerek üst mahkemede yeniden incelenmesinin istenmesidir; bu, adil yargılanmanın bir güvencesidir." },
{ id: "vat-027", konu: "Yargı ve İdare", soru: "Herkesin, hakkı çiğnendiğinde yasal yollarla mahkemeye başvurabilmesi aşağıdaki haklardan hangisiyle ilgilidir?", secenekler: ["Seçme hakkı", "Dinlenme hakkı", "Mülkiyet hakkı", "Konut dokunulmazlığı", "Hak arama özgürlüğü"], dogru: 4, aciklama: "Hak arama özgürlüğü, herkesin meşru yollarla yargı organlarına başvurabilmesini güvence altına alan temel bir haktır." }
);
