window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["vatandaslik"] = window.KPSS_BANK["vatandaslik"] || []).push(
{ id: "vat-010", konu: "Hukukun Temel Kavramları", soru: "Aşağıdakilerden hangisi bir hukuk kuralıdır?", secenekler: ["Büyüklerle karşılaşınca selam vermek", "Trafikte kırmızı ışıkta durmak", "Sofrada uyulan görgü kuralları", "Misafire ikramda bulunmak", "Bayramda büyüklerin elini öpmek"], dogru: 1, aciklama: "Trafikte kırmızı ışıkta durmak, uyulmadığında devletin yaptırım (ceza) uyguladığı bir hukuk kuralıdır. Diğerleri görgü ve ahlak kurallarıdır; bunların yaptırımı manevidir." },
{ id: "vat-011", konu: "Anayasa ve Genel Esaslar", soru: "Türkiye Cumhuriyeti'nin başkenti aşağıdakilerden hangisidir?", secenekler: ["İstanbul", "İzmir", "Bursa", "Antalya", "Ankara"], dogru: 4, aciklama: "Türkiye Cumhuriyeti'nin başkenti, 13 Ekim 1923'te başkent ilan edilen Ankara'dır." },
{ id: "vat-012", konu: "Anayasa ve Genel Esaslar", soru: "Bir devletin temel yapısını, yönetim biçimini ve vatandaşların temel hak ile ödevlerini düzenleyen en üstün hukuk kuralları bütününe ne ad verilir?", secenekler: ["Yönetmelik", "Genelge", "Tüzük", "Anayasa", "Tebliğ"], dogru: 3, aciklama: "Anayasa, bir devletin temel yapısını ve vatandaşların hak ve ödevlerini düzenleyen en üstün hukuk kurallarıdır; diğer bütün kurallar ona uygun olmak zorundadır." },
{ id: "vat-013", konu: "Temel Hak ve Ödevler", soru: "Aşağıdakilerden hangisi bir temel hak ve özgürlüktür?", secenekler: ["Yaşama hakkı", "Vergi vermek", "Askerlik yapmak", "Kanunlara uymak", "Trafik cezasını ödemek"], dogru: 0, aciklama: "Yaşama hakkı, en temel ve dokunulmaz haklardandır. Vergi vermek, askerlik ve kanunlara uymak ise hak değil, birer vatandaşlık ödevidir." },
{ id: "vat-014", konu: "Temel Hak ve Ödevler", soru: "Bir kişinin düşüncelerini serbestçe açıklayabilmesi aşağıdaki özgürlüklerden hangisiyle ilgilidir?", secenekler: ["Seyahat özgürlüğü", "Konut dokunulmazlığı", "Düşünce ve ifade özgürlüğü", "Vergi ödevi", "Askerlik görevi"], dogru: 2, aciklama: "Düşünceyi serbestçe açıklayabilme, düşünce ve ifade özgürlüğüyle ilgilidir; bu, demokratik toplumun temel haklarından biridir." },
{ id: "vat-015", konu: "Yasama", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde milletvekili genel seçimleri kaç yılda bir yapılır?", secenekler: ["4", "5", "6", "7", "3"], dogru: 1, aciklama: "2017 Anayasa değişikliğinden sonra milletvekili genel seçimleri 5 yılda bir yapılır." },
{ id: "vat-016", konu: "Yürütme", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde Cumhurbaşkanı kaç yıllığına ve kim tarafından seçilir?", secenekler: ["4 yıllığına, TBMM tarafından", "7 yıllığına, ordu tarafından", "Ömür boyu, kendi kararıyla", "6 yıllığına, mahkemeler tarafından", "5 yıllığına, halk tarafından"], dogru: 4, aciklama: "Cumhurbaşkanı, halk tarafından 5 yıllığına seçilir ve bir kişi en fazla iki dönem bu görevi yürütebilir." },
{ id: "vat-017", konu: "Yürütme", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde aşağıdakilerden hangisi Cumhurbaşkanı tarafından atanır?", secenekler: ["Milletvekilleri", "Bütün hâkimler", "Belediye başkanları", "Bakanlar ve Cumhurbaşkanı yardımcıları", "Muhtarlar"], dogru: 3, aciklama: "Bu sistemde bakanları ve Cumhurbaşkanı yardımcılarını Cumhurbaşkanı atar. Milletvekilleri, belediye başkanları ve muhtarlar ise halk tarafından seçilir." },
{ id: "vat-018", konu: "Yargı ve İdare", soru: "Suç işlediği ileri sürülen bir kişinin, suçu mahkeme kararıyla kesinleşene kadar suçsuz sayılması ilkesine ne ad verilir?", secenekler: ["Masumiyet (suçsuzluk) karinesi", "Kanunilik ilkesi", "Eşitlik ilkesi", "Egemenlik ilkesi", "Laiklik ilkesi"], dogru: 0, aciklama: "Masumiyet (suçsuzluk) karinesi, bir kişinin suçluluğu kesinleşmeden suçlu sayılamayacağı ilkesidir; adil yargılanmanın temel güvencelerinden biridir." }
);
