window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["vatandaslik"] = window.KPSS_BANK["vatandaslik"] || []).push(
{ id: "vat-028", konu: "Hukukun Temel Kavramları", soru: "Toplumda uyulması beklenen, uyulmadığında ayıplama ve kınama gibi manevi bir tepkiyle karşılaşılan kurallara ne ad verilir?", secenekler: ["Hukuk kuralları", "Ahlak ve görgü kuralları", "Kanunlar", "Yönetmelikler", "Anayasa hükümleri"], dogru: 1, aciklama: "Ahlak ve görgü kurallarının yaptırımı manevidir (ayıplama, kınama). Hukuk kurallarının yaptırımı ise devlet gücüne dayalı, maddi bir yaptırımdır." },
{ id: "vat-029", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre Türkiye Devleti'nin yönetim biçimi aşağıdakilerden hangisidir?", secenekler: ["Cumhuriyet", "Krallık", "İmparatorluk", "Federasyon", "Meşrutiyet"], dogru: 0, aciklama: "Anayasa'ya göre Türkiye Devleti bir Cumhuriyettir; bu ilke Anayasa'nın değiştirilemez maddeleri arasındadır." },
{ id: "vat-030", konu: "Yürütme", soru: "1982 Anayasası'na göre yürütme yetkisi ve görevi kime aittir?", secenekler: ["TBMM'ye", "Cumhurbaşkanına", "Yüksek mahkemelere", "Belediyelere", "Muhtarlara"], dogru: 1, aciklama: "Cumhurbaşkanlığı Hükûmet Sistemi'nde yürütme yetkisi ve görevi Cumhurbaşkanı'na aittir; Cumhurbaşkanı hem devletin hem yürütmenin başıdır." },
{ id: "vat-031", konu: "Temel Hak ve Ödevler", soru: "Kişinin özel yaşamına, mektuplarına ve telefon görüşmelerine izinsiz karışılamaması aşağıdaki haklardan hangisiyle ilgilidir?", secenekler: ["Özel hayatın gizliliği ve haberleşme özgürlüğü", "Seçme ve seçilme hakkı", "Vergi verme ödevi", "Askerlik görevi", "Eğitim hakkı"], dogru: 0, aciklama: "Özel hayatın gizliliği ve haberleşme özgürlüğü; kişinin özel yaşamına, mektup ve iletişimine izinsiz karışılamamasını güvence altına alan kişisel haklardandır." },
{ id: "vat-032", konu: "Temel Hak ve Ödevler", soru: "Herkesin eğitim ve öğrenim hakkından yararlanabilmesi hangi tür haklardandır?", secenekler: ["Siyasi haklar", "Kişisel (koruyucu) haklar", "Sosyal ve ekonomik haklar", "Vatandaşlık ödevleri", "Yaptırımlar"], dogru: 2, aciklama: "Eğitim ve öğrenim hakkı, devletten hizmet beklenen sosyal ve ekonomik haklardandır. Bu haklar bireyin toplum içinde daha iyi yaşamasını amaçlar." },
{ id: "vat-033", konu: "Yasama", soru: "Devletin bir yıllık gelir ve giderlerini gösteren bütçe kanununu görüşüp kabul etme görevi aşağıdakilerden hangisine aittir?", secenekler: ["Cumhurbaşkanı", "Danıştay", "Belediye başkanı", "TBMM", "Vali"], dogru: 3, aciklama: "Bütçe kanununu görüşüp kabul etmek TBMM'nin (yasama organının) görevlerindendir; bu, meclisin devleti denetleme yollarından biridir." },
{ id: "vat-034", konu: "Yürütme", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde bir kişi en fazla kaç dönem Cumhurbaşkanı seçilebilir?", secenekler: ["1", "3", "4", "2", "Sınırsız"], dogru: 3, aciklama: "Bir kişi en fazla iki dönem Cumhurbaşkanı seçilebilir; her dönem 5 yıldır." },
{ id: "vat-035", konu: "Yargı ve İdare", soru: "Devlet kurumlarının işlem ve eylemlerine karşı açılan davalara bakan yargı koluna ne ad verilir?", secenekler: ["Adli yargı", "Anayasa yargısı", "Askerî yargı", "Ceza yargısı", "İdari yargı"], dogru: 4, aciklama: "İdari yargı, devlet kurumlarının (idarenin) işlemlerine karşı açılan davalara bakar; en üst mahkemesi Danıştay'dır. Adli yargı ise kişiler arası hukuk ve ceza davalarına bakar." },
{ id: "vat-036", konu: "Yargı ve İdare", soru: "Anayasa Mahkemesi kaç üyeden oluşur?", secenekler: ["11", "13", "15", "17", "22"], dogru: 2, aciklama: "Anayasa Mahkemesi 15 üyeden oluşur; üyelerin çoğunu Cumhurbaşkanı, bir kısmını ise TBMM seçer." }
);
