window.KPSS_BANK = window.KPSS_BANK || {};
(window.KPSS_BANK["vatandaslik"] = window.KPSS_BANK["vatandaslik"] || []).push(
{ id: "vat-001", konu: "Hukukun Temel Kavramları", soru: "Bir hukuk kuralına uyulmadığında devletin uyguladığı zorlayıcı tepkiye (ceza, para cezası gibi) ne ad verilir?", secenekler: ["Yaptırım", "Örf", "Gelenek", "Ahlak kuralı", "Görgü kuralı"], dogru: 0, aciklama: "Yaptırım, bir hukuk kuralının çiğnenmesi hâlinde devletin uyguladığı zorlayıcı tepkidir; hukuk kurallarını ahlak ve görgü kurallarından ayıran temel özelliktir." },
{ id: "vat-002", konu: "Anayasa ve Genel Esaslar", soru: "Türkiye Cumhuriyeti'nde egemenlik kayıtsız şartsız kime aittir?", secenekler: ["Cumhurbaşkanına", "Millete", "Orduya", "Mahkemelere", "Bakanlar Kuruluna"], dogru: 1, aciklama: "Anayasa'ya göre egemenlik kayıtsız şartsız milletindir; millet bu yetkiyi yetkili organlar aracılığıyla kullanır." },
{ id: "vat-003", konu: "Anayasa ve Genel Esaslar", soru: "1982 Anayasası'na göre aşağıdakilerden hangisi Türkiye Cumhuriyeti'nin niteliklerinden biri değildir?", secenekler: ["Demokratik devlet", "Laik devlet", "Sosyal devlet", "Hukuk devleti", "Federal devlet"], dogru: 4, aciklama: "Türkiye üniter (tek) bir devlettir; federal değildir. Anayasa'ya göre Türkiye demokratik, laik, sosyal bir hukuk devletidir." },
{ id: "vat-004", konu: "Temel Hak ve Ödevler", soru: "Aşağıdakilerden hangisi bir vatandaşlık ödevidir?", secenekler: ["Seçme hakkı", "Konut dokunulmazlığı", "Vergi ödemek", "Dilekçe hakkı", "Özel hayatın gizliliği"], dogru: 2, aciklama: "Vergi ödemek, vatandaşın temel ödevlerindendir. Diğer seçenekler ödev değil, birer haktır." },
{ id: "vat-005", konu: "Temel Hak ve Ödevler", soru: "Aşağıdakilerden hangisi sosyal ve ekonomik haklardan biridir?", secenekler: ["Konut dokunulmazlığı", "Kişi güvenliği", "Seçme ve seçilme hakkı", "Eğitim ve sağlık hakkı", "Düşünceyi açıklama özgürlüğü"], dogru: 3, aciklama: "Eğitim ve sağlık hakkı, devletten hizmet beklenen sosyal-ekonomik haklardandır. Kişi güvenliği kişisel, seçme-seçilme ise siyasi haktır." },
{ id: "vat-006", konu: "Yasama", soru: "Kanun yapma (yasama) yetkisi aşağıdakilerden hangisine aittir?", secenekler: ["Cumhurbaşkanı", "TBMM", "Danıştay", "Yargıtay", "Bakanlar"], dogru: 1, aciklama: "Yasama yetkisi, Türk Milleti adına Türkiye Büyük Millet Meclisi'nindir ve devredilemez." },
{ id: "vat-007", konu: "Yasama", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde TBMM kaç milletvekilinden oluşur?", secenekler: ["400", "450", "500", "550", "600"], dogru: 4, aciklama: "2017 Anayasa değişikliğinden sonra TBMM 600 milletvekilinden oluşur." },
{ id: "vat-008", konu: "Yürütme", soru: "Cumhurbaşkanlığı Hükûmet Sistemi'nde yürütmenin başı aşağıdakilerden hangisidir?", secenekler: ["Başbakan", "Meclis Başkanı", "Cumhurbaşkanı", "Genelkurmay Başkanı", "Adalet Bakanı"], dogru: 2, aciklama: "Bu sistemde yürütme yetkisi Cumhurbaşkanı'na aittir; Cumhurbaşkanı hem devletin hem yürütmenin başıdır. Başbakanlık makamı kaldırılmıştır." },
{ id: "vat-009", konu: "Yargı ve İdare", soru: "Hukuk ve ceza davalarına bakan mahkemelerin (adli yargının) en üst mahkemesi aşağıdakilerden hangisidir?", secenekler: ["Yargıtay", "Danıştay", "Sayıştay", "Anayasa Mahkemesi", "Uyuşmazlık Mahkemesi"], dogru: 0, aciklama: "Yargıtay, adli yargının (hukuk ve ceza) en üst mahkemesidir. Danıştay idari yargının, Sayıştay ise mali denetimin üst organıdır." }
);
